#!/bin/sh

if [ "${0#/}" = "${0}" ]
then
    MK_HOME="`pwd`/`dirname "${0}"`"
else
    MK_HOME="`dirname "${0}"`"
fi

SHELL_CANDIDATES='/bin/dash /usr/bin/bash /usr/local/bin/bash /bin/sh'

for _shell in ${SHELL_CANDIDATES}
do
    if [ -x "$_shell" ]
    then
	MK_SHELL="$_shell"
	break
    fi
done

export MK_HOME MK_SHELL

$MK_SHELL "${MK_HOME}/configure.sh" "$@"
