#!/bin/sh

if type readlink >/dev/null 2>&1 && [ -h "$0" ]
then
    _SELF="`readlink "$0"`"
else
    _SELF="$0"
fi

if [ "${_SELF#/}" = "${_SELF}" ]
then
    MK_HOME="`pwd`/`dirname "${_SELF}"`"
else
    MK_HOME="`dirname "${_SELF}"`"
fi

SHELL_CANDIDATES='/bin/dash /usr/bin/bash /usr/local/bin/bash /bin/sh'

for _shell in ${SHELL_CANDIDATES}
do
    if [ -x "$_shell" ]
    then
	MK_SHELL="$_shell"
	break
    fi
done

export MK_HOME MK_SHELL

$MK_SHELL "${MK_HOME}/configure.sh" "$@"
