#!/bin/sh

if [ -z "$MK_HOME" ]
then
    dir="`dirname "$0"`"
    if [ -d "${dir}" -a -d "${dir}/pylib" ]
    then
	MK_HOME="`(cd "$dir" && pwd)`"
    else
	echo "Could not determine MetaKit home directory."
	echo "Please set MK_HOME to the location of MetaKit."
	exit 1
    fi
fi

PYTHONPATH="$PYTHONPATH:${MK_HOME}/pylib"

export MK_HOME
export PYTHONPATH

python -m mk.init "$@"
