# MK_ROOT_DIR and MK_WORK_DIR must be defined at this point
MK_SOURCE_DIR="${MK_ROOT_DIR}/${MK_SOURCE_DIRNAME}"
MK_STAGE_DIR="${MK_WORK_DIR}/${MK_STAGE_DIRNAME}"
MK_BUILD_DIR="${MK_WORK_DIR}/${MK_BUILD_DIRNAME}"
MK_RESOURCE_DIR="${MK_ROOT_DIR}/${MK_RESOURCE_DIRNAME}"
MK_COMPONENT_DIR="${MK_RESOURCE_DIR}/${MK_COMPONENT_DIRNAME}"
MK_MODULE_DIR="${MK_RESOURCE_DIR}/${MK_MODULE_DIRNAME}"

MK_CONFIG_FILE="${MK_WORK_DIR}/${MK_CONFIG_FILENAME}"
MK_CONFIGURE_FILE="${MK_ROOT_DIR}/${MK_CONFIGURE_FILENAME}"
MK_ACTION_FILE="${MK_WORK_DIR}/${MK_ACTION_FILENAME}"
MK_MAKEFILE_FILE="${MK_WORK_DIR}/${MK_MAKEFILE_FILENAME}"
MK_MANIFEST_FILE="${MK_ROOT_DIR}/${MK_MANIFEST_FILENAME}"