#!/bin/sh

MK_DEFAULT_HOME="@MK_DEFAULT_HOME@"
MK_SOURCE_DIR="`dirname "$0"`"

if test -d "$MK_HOME"
then
    :
elif test -d "$MK_DEFAULT_HOME"
then
    MK_HOME="${MK_DEFAULT_HOME}"
elif test -d "${MK_SOURCE_DIR}/mk"
then
    MK_HOME="${MK_SOURCE_DIR}/mk"
else
    echo "ERROR: could not find valid MK_HOME"
    exit 1
fi

SHELL_CANDIDATES="$MK_SHELL /bin/dash /usr/bin/bash /usr/local/bin/bash /bin/sh"

for _shell in ${SHELL_CANDIDATES}
do
    if [ -x "$_shell" ]
    then
	MK_SHELL="$_shell"
	break
    fi
done

if test -z "$MK_SHELL"
then
    echo "ERROR: could not find valid MK_SHELL"
    exit 1
fi

export MK_HOME MK_SHELL MK_SOURCE_DIR
exec $MK_SHELL "${MK_HOME}/configure.sh" "$@"
